# Generated by Django 2.2.10 on 2020-05-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timenew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
