# Generated by Django 2.2.10 on 2020-05-16 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_timenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timenew',
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
