# Generated by Django 2.2.10 on 2020-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200516_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.CharField(max_length=40),
        ),
    ]
